// <auto-generated />
using System;
using FocusBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321192231_RenameDescriptionColumn")]
    partial class RenameDescriptionColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FocusBot.Core.Entities.AlignmentCacheEntry", b =>
                {
                    b.Property<string>("ContextHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContextHash", "TaskContentHash");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AlignmentCacheEntries");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.UserSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextSwitchCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DistractedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistractionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FocusScorePercent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FocusedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopAlignedApps")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopDistractingApps")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalElapsedSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("IsCompleted");

                    b.ToTable("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
