// <auto-generated />
using System;
using FocusBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213120000_AddFocusScoreAndSegments")]
    partial class AddFocusScoreAndSegments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FocusBot.Core.Entities.AlignmentCacheEntry", b =>
                {
                    b.Property<string>("ContextHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContextHash", "TaskContentHash");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AlignmentCacheEntries");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.FocusSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlignmentScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskId", "ContextHash", "AlignmentScore")
                        .IsUnique();

                    b.ToTable("FocusSegments");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.UserTask", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FocusScorePercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalElapsedSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.HasIndex("Status");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.WindowContext", b =>
                {
                    b.Property<string>("ContextHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ContextHash");

                    b.ToTable("WindowContexts");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.AlignmentCacheEntry", b =>
                {
                    b.HasOne("FocusBot.Core.Entities.WindowContext", null)
                        .WithMany()
                        .HasForeignKey("ContextHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
