// <auto-generated />
using System;
using FocusBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FocusBot.Core.Entities.AlignmentCacheEntry", b =>
                {
                    b.Property<string>("ContextHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContextHash", "TaskContentHash");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AlignmentCacheEntries");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.DailyFocusAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AnalyticsDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AverageDistractionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistractedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistractionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FocusedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTrackedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnclearSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnalyticsDateLocal")
                        .IsUnique();

                    b.ToTable("DailyFocusAnalytics");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.DistractionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistractedDurationSecondsAtEmit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitleSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "OccurredAtUtc");

                    b.HasIndex("TaskId", "OccurredAtUtc");

                    b.ToTable("DistractionEvents");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.FocusSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlignmentScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AnalyticsDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskId", "ContextHash", "AlignmentScore", "AnalyticsDateLocal")
                        .IsUnique();

                    b.ToTable("FocusSegments");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.UserTask", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextSwitchCostSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("DistractedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistractionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FocusScorePercent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FocusedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopDistractingApps")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalElapsedSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.HasIndex("IsCompleted");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.WindowContext", b =>
                {
                    b.Property<string>("ContextHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ContextHash");

                    b.ToTable("WindowContexts");
                });

            modelBuilder.Entity("FocusBot.Core.Entities.AlignmentCacheEntry", b =>
                {
                    b.HasOne("FocusBot.Core.Entities.WindowContext", null)
                        .WithMany()
                        .HasForeignKey("ContextHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
